workspace(name = "serving")

local_repository(
    name = "tf_serving",
    path = "tf_serving",
)

local_repository(
    name = "org_tensorflow",
    path = "tf_serving/tensorflow",
)

load('@org_tensorflow//tensorflow:workspace.bzl', 'tf_workspace')
tf_workspace()

bind(
    name = "libssl",
    actual = "@boringssl//:ssl",
)

bind(
    name = "zlib",
    actual = "@zlib_archive//:zlib",
)

# only needed for inception model export

local_repository(
    name = "inception_model",
    path = "tf_serving/tf_models/inception",
)
